### ISSUE TITLE
Provided config.json has format error

### ISSUE THREAD

**Issue by roboterm** [grover/homebridge-telegram#6] opened 2018-03-12 10:05 UTC
tip: count the brackets

**Comment by grover** [comment] 2018-03-13 17:56
Since you already know where the issue is and my time is limited - how about contributing the necessary change and creating a pull request?

**Comment by grover** [comment] 2018-03-20 23:49
Thanks for the PR. I merged it with slight modifications.

**Closed by grover** 2018-03-20 23:49 UTC
Labels: bug, good first issue, help wanted
